modLoader = "javafml"
loaderVersion = "*"
#issueTrackerURL = ""
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "${authors}"
description = '''
${description}
'''
logoFile = "assets/${id}/icon.png"
logoBlur = false

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = ${minecraftVersionRange}
ordering = "NONE"
side = "BOTH"
